import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import repositories.IRepository;

import repositories.IRepositoryServer;
import repositories.impl.HeroBuilder;
import repositories.impl.HeroRepository;

import repositories.impl.RepositoryServer;
import unitofwork.IUnitOfWork;
import unitofwork.UnitOfWork;
import domain.*;


public class Main {

	public static void main(String[] args) {
	
	
	
	
	String url="jdbc:mysql://localhost/workdb";
	Hero Drizzt = new Hero();
	Drizzt.setName("Drizzt");
	Drizzt.setProfession("Blade Dancer");
	Drizzt.setHP(3000);
	Drizzt.setMP(1000);
	Drizzt.setEXP(9999);
	
	String username = "root";
	String password = "";
	try {
		
		Connection connection = DriverManager.getConnection(url, username,password);
		IUnitOfWork uow = new UnitOfWork(connection);
	/*	
		String createTableSql = 
				"CREATE TABLE Heroes("
				+ "id int GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20),"
				+ "profession VARCHAR(20),"
				+ "hp int,"
				+ "mp int,"
				+ "exp int"	
				+ ")";
		Statement createTable = connection.createStatement();
		createTable.executeUpdate(createTableSql);		
		*/
		IRepositoryServer server = new RepositoryServer(connection, uow);
		
		server.getHeroes().save(Drizzt);
		
		List<Hero> heroesFromDb= server.getHeroes().getAll();
		
		for(Hero heroFromDb: heroesFromDb)
			System.out.println(heroFromDb.getId()+" "+heroFromDb.getName()+" "+heroFromDb.getProfession()+" "+heroFromDb.getHP()+" "+heroFromDb.getMP()+" "+heroFromDb.getEXP());
		
	
		for(Hero heroFromDb: server.getHeroes().getAll())
			System.out.println(heroFromDb.getId()+" "+heroFromDb.getName()+" "+heroFromDb.getProfession()+" "+heroFromDb.getHP()+" "+heroFromDb.getMP()+" "+heroFromDb.getEXP());
		
		
		
	} catch (SQLException e) {
		e.printStackTrace();
	}
	System.out.println("koniec");
}
	
	
	
	
}

