import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;

import repositories.IRepository;
import repositories.impl.HeroBuilder;
import repositories.impl.HeroRepository;
import domain.*;


public class Main {

	public static void main(String[] args) {
	
	
	
	
	String url="jdbc:hsqldb:hsql://localhost/workdb";
	Hero Drizzt = new Hero();
	Drizzt.setName("Drizzt");
	Drizzt.setProfession("Blade Dancer");
	Drizzt.setHP(3000);
	Drizzt.setMP(1000);
	Drizzt.setEXP(99999);
	try {
		
		Connection connection = DriverManager.getConnection(url);
		
		String createTableSql = 
				"CREATE TABLE Heroes("
				+ "id int GENERATED BY DEFAULT AS IDENTITY,"
				+ "name VARCHAR(20),"
				+ "profession VARCHAR(20)"
				+ "hp int"
				+ "mp int"
				+ "exp int"	
				+ ")";
		Statement createTable = connection.createStatement();
		createTable.executeUpdate(createTableSql);
		
		IRepository<Hero> heroes = new HeroRepository(connection, new HeroBuilder());
		heroes.save(Drizzt);
		List<Hero> heroesFromDb= heroes.getAll();
		
		for(Hero heroFromDb: heroesFromDb)
			System.out.println(heroFromDb.getId()+" "+heroFromDb.getName()+" "+heroFromDb.getProfession()+" "+heroFromDb.getHP()+" "+heroFromDb.getMP()+" "+heroFromDb.getEXP());
		
		Hero h = heroes.get(2);
		h.setProfession("Drow");
		heroes.update(h);
		heroes.delete(heroesFromDb.get(0));
		
		for(Hero heroFromDb: heroes.getAll())
			System.out.println(heroFromDb.getId()+" "+heroFromDb.getName()+" "+heroFromDb.getProfession()+" "+heroFromDb.getHP()+" "+heroFromDb.getMP()+" "+heroFromDb.getEXP());
		
		
		
	} catch (SQLException e) {
		e.printStackTrace();
	}
	System.out.println("koniec");
}
	
	
	
	
}

